logger:
  mode: none
  level: warn
  syslog_on: true

  single:
    path: /tmp/ifman.log
    permit: 0644

  rotate:
    dir: /tmp/ifman
    max_age_sec: 1296000
    period_sec: 86400

interface:

addr:

rp_filter:

learning:

common:
  check_period_sec: 10
