#!/bin/sh /etc/rc.common
# Copyright (C) XUEGAONET Harris <i@xuegaogg.com>

START=21
STOP=21
USE_PROCD=1

PROG=/bin/ifman
CONFIG=/etc/config/ifman

start_service() {
        [ -f ${CONFIG} ] || return 1
        procd_open_instance
        procd_set_param command ${PROG} -config ${CONFIG}
        procd_set_param respawn
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
}

